### ISSUE TITLE
Consider numbering folder names in tasks

### ISSUE THREAD

**Issue by tyilo** [Mortal/csaudk-submitj#12]
For instance instead of
```
maze
mingap
rpn
```

it would be

```
07-rpn
12-mingap
19-maze
```

so they are sorted by when they appear in the handins, I guess?

(the numbers used are arbitrary)

**Comment by Mortal** [comment]
The same tasks will probably be used next year, but maybe in a different order. Maybe additional tasks will be added. I don't think the directories should be numbered.

**Comment by tyilo** [comment]
And another would be to have a README in tasks listing the order of the tasks, which could be updated each year.

**Comment by Mortal** [comment]
That's a nice idea. Implemented in 37fda7eefb119a10548b4c92914d1fbef7cc0308. Thanks!
